server:
  port: ${PORT:0}

spring:
  application:
    name: ms-students

eureka:
  instance:
    hostname: localhost
    instance-id:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka